### lesson 30 Orthogonal Matrix

In [2]:
import numpy as np
import torch

Question 3

In [20]:
#numpy

I3 = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(I3)

print('dot product col 0,1')
print('0,1')
np.dot(I3[0], I3[1])


[[1 0 0]
 [0 1 0]
 [0 0 1]]
dot product col 0,1
0,1


0

In [21]:
print('dot product of col 1,2')
np.dot(I3[1], I3[2])

dot product of col 1,2


0

In [22]:
print('dot product of col 0,2')
np.dot(I3[0], I3[2])

dot product of col 0,2


0

dot products are 0. all columns are orthogonal to each other

In [23]:
print('L2norm of col0')
np.linalg.norm(I3[0])


L2norm of col0


1.0

In [24]:
print('L2norm of col1')
np.linalg.norm(I3[1])

L2norm of col1


1.0

In [25]:
print('L2norm of col2')
np.linalg.norm(I3[2])

L2norm of col2


1.0

In [27]:
K = torch.tensor([[2/3,1/3,2/3],[-2/3,2/3,1/3],[1/3,2/3,-2/3]])
K

tensor([[ 0.6667,  0.3333,  0.6667],
        [-0.6667,  0.6667,  0.3333],
        [ 0.3333,  0.6667, -0.6667]])

In [28]:
print('dot product of col 0 ,1')
torch.dot(K[0], K[1])

dot prodict of col 0 ,1


tensor(0.)

In [29]:
print('dot product of col 1 ,2')
torch.dot(K[1], K[2])

dot prodict of col 1 ,2


tensor(0.)

In [35]:
print('dot product of col 0 ,2')
torch.dot(K[0], K[2])

dot product of col 0 ,2


tensor(0.)

In [32]:
print('norm of col 0')
torch.norm(K[0])

norm of col 0, 1


tensor(1.)

In [33]:
print('norm of col 1')
torch.norm(K[1])

norm of col 1


tensor(1.)

In [34]:
print('norm of col 2')
torch.norm(K[2])

norm of col 2


tensor(1.)

**Exercises**:

1. Use PyTorch to confirm $Xv = \lambda v$ for the first eigenvector of $X$.
2. Confirm $Xv = \lambda v$ for the remaining eigenvectors of $X$ (you can use NumPy or PyTorch, whichever you prefer).

In [39]:
X = torch.tensor([[25.0, 2, 9], [5.0, 26, -5], [3.0, 7, -1]], dtype = torch.float)
X

tensor([[25.,  2.,  9.],
        [ 5., 26., -5.],
        [ 3.,  7., -1.]])

In [66]:
L= torch.linalg.eig(X)
L

torch.return_types.linalg_eig(
eigenvalues=tensor([29.6762+0.j, 20.6212+0.j, -0.2974+0.j]),
eigenvectors=tensor([[ 0.7118+0.j,  0.6502+0.j, -0.3422+0.j],
        [ 0.6665+0.j, -0.7446+0.j,  0.2379+0.j],
        [ 0.2217+0.j, -0.1509+0.j,  0.9090+0.j]]))

In [67]:
L, V = L[0], L[1]

In [68]:
L #eigenvalues
L = L.type(torch.float)
L

tensor([29.6762, 20.6212, -0.2974])

In [69]:
V #eigenvectors
V = V.type(torch.float)
V

tensor([[ 0.7118,  0.6502, -0.3422],
        [ 0.6665, -0.7446,  0.2379],
        [ 0.2217, -0.1509,  0.9090]])

In [76]:
v_first =  V[:,0]
v_first

tensor([0.7118, 0.6665, 0.2217])

In [77]:
L_first = L[0]
L_first

tensor(29.6762)

In [80]:
L_first*v_first

tensor([21.1223, 19.7798,  6.5792])

In [81]:
torch.matmul(X,v_first)

tensor([21.1223, 19.7798,  6.5792])

## lesson 39

**Exercises**:

1. Use PyTorch to decompose the matrix $P$ (below) into its components $V$, $\Lambda$, and $V^{-1}$. Confirm that $P = V \Lambda V^{-1}$.
2. Use PyTorch to decompose the symmetric matrix $S$ (below) into its components $Q$, $\Lambda$, and $Q^T$. Confirm that $S = Q \Lambda Q^T$.

In [3]:
import torch

In [4]:
P = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [8]:
ldas, v = torch.linalg.eig(P)

In [9]:
ldas

tensor([23.7644+0.j,  6.6684+0.j, -3.4328+0.j])

In [12]:
lda_ = torch.diag(ldas)

In [13]:
lda_

tensor([[23.7644+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  6.6684+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -3.4328+0.j]])

In [15]:
v_inv = torch.inverse(v)

In [16]:
v_inv

tensor([[ 1.1356+0.j,  0.0102+0.j, -0.2868+0.j],
        [ 0.3914+0.j, -0.7198-0.j, -1.0032+0.j],
        [ 0.0817+0.j, -1.1164-0.j,  0.2052+0.j]])

In [18]:
torch.matmul(v, torch.matmul(lda_, v_inv))

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 3.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [ 5.0000+0.j,  7.0000+0.j,  4.0000+0.j]])

2. Use PyTorch to decompose the symmetric matrix $S$ (below) into its components $Q$, $\Lambda$, and $Q^T$. Confirm that $S = Q \Lambda Q^T$.

In [38]:
S = torch.tensor([[25, 2, -5], [2, -2, 1], [-5, 1, 4.]])
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [39]:
ldas, v = torch.linalg.eig(S)

In [40]:
ldas

tensor([26.2361+0.j,  3.2435+0.j, -2.4796+0.j])

In [49]:
lda_ = torch.diag(ldas)

In [42]:
lda_

tensor([[26.2361+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  3.2435+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -2.4796+0.j]])

In [45]:
S_t = torch.t(S)

In [46]:
S_t

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [50]:
torch.matmul(S, torch.matmul(S_t,lda_))

RuntimeError: expected scalar type Float but found ComplexFloat

### lesson 42 Singular Value Decomposition
**Exercise**: Using the matrix `P` from the preceding PyTorch exercises, demonstrate that these three SVD-eigendecomposition equations are true. 

In [1]:
import torch

In [2]:
P = torch.tensor([[25,4,-5],[3,-2,1],[5,7,4.]])

In [3]:
P

tensor([[25.,  4., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [4]:
u,d,vt = torch.linalg.svd(P)

In [5]:
u

tensor([[-0.9730,  0.1974,  0.1193],
        [-0.0894,  0.1539, -0.9840],
        [-0.2126, -0.9682, -0.1321]])

In [15]:
d

tensor([26.4718,  7.8794,  2.6752])

In [18]:
new_d = torch.diag(d)

In [19]:
new_d

tensor([[26.4718,  0.0000,  0.0000],
        [ 0.0000,  7.8794,  0.0000],
        [ 0.0000,  0.0000,  2.6752]])

In [7]:
vt

tensor([[-0.9692, -0.1965,  0.1483],
        [ 0.0706, -0.7989, -0.5972],
        [-0.2358,  0.5684, -0.7882]])

In [13]:
temp =torch.matmul(u,d)

In [21]:
torch.matmul(torch.matmul(u,new_d), vt)

tensor([[25.0000,  4.0000, -5.0000],
        [ 3.0000, -2.0000,  1.0000],
        [ 5.0000,  7.0000,  4.0000]])

### Lesson 46 Trace Operator


With the matrix `A_p` provided below: 

1. Use the PyTorch trace method to calculate the trace of `A_p`.
2. Use the PyTorch Frobenius norm method and the trace method to demonstrate that $||A||_F = \sqrt{\mathrm{Tr}(AA^\mathrm{T})}$


In [19]:
import torch
from math import sqrt
A_p = torch.tensor([[-1.,  2.],[ 3., -2.],[ 5.,  7.]])

In [20]:
A_p

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [12]:
torch.trace(A_p)

tensor(-3.)

In [13]:
# frobenious norm of A
torch.linalg.matrix_norm(A_p)

tensor(9.5917)

In [22]:
A_t = torch.transpose(A_p,0,1)
A_t

tensor([[-1.,  3.,  5.],
        [ 2., -2.,  7.]])

In [25]:
pdt = torch.matmul(A_p, A_t)

In [26]:
sqrt(torch.trace(pdt))

9.591663046625438